import { Stock } from "@/types";

export const defaultStocks: Stock[] = [
  {
    id: 0,
    name: "Olie Baronen",
    shortName: "OLIE",
    value: 50,
    defaultValue: 50,
    min: 15,
    max: 500,
    volatile: 0.012,
    historical: [],
    color: "#e23670",
  },
  {
    id: 1,
    name: "Amager Airlines",
    shortName: "SKRT",
    value: 30,
    defaultValue: 30,
    min: 10,
    max: 300,
    volatile: 0.012,
    historical: [],
    color: "#2eb88a",
  },
  {
    id: 2,
    name: "Hundekrone",
    shortName: "DOGE",
    value: 10,
    defaultValue: 10,
    min: 1,
    max: 100,
    volatile: 0.017,
    historical: [],
    color: "#e88c30",
  },
  {
    id: 3,
    name: "Nuclear Power",
    shortName: "BOOM",
    value: 35,
    defaultValue: 35,
    min: 10,
    max: 800,
    volatile: 0.012,
    historical: [],
    color: "#af57db",
  },
  {
    id: 4,
    name: "Faxe Kondi",
    shortName: "FAXE",
    value: 20,
    defaultValue: 20,
    min: 3,
    max: 140,
    volatile: 0.014,
    historical: [],
    color: "#2662d9",
  },
];
